// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd8V9RE3ZvYu7Vih3xuRBMZao1lhYg28o',
    appId: '1:715110019947:web:88577630a03721b01bd22e',
    messagingSenderId: '715110019947',
    projectId: 'apps-3e547',
    authDomain: 'apps-3e547.firebaseapp.com',
    storageBucket: 'apps-3e547.appspot.com',
    measurementId: 'G-X7LKLXWN1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-P5WijbcTLZKeWJtC-Fjbo5ywl0OyWV0',
    appId: '1:715110019947:android:2867794de011440d1bd22e',
    messagingSenderId: '715110019947',
    projectId: 'apps-3e547',
    storageBucket: 'apps-3e547.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKbrLYJu5EaQuf7fOI0v-zAzHqOtEFaN4',
    appId: '1:715110019947:ios:a0e6436c6b53ab871bd22e',
    messagingSenderId: '715110019947',
    projectId: 'apps-3e547',
    storageBucket: 'apps-3e547.appspot.com',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKbrLYJu5EaQuf7fOI0v-zAzHqOtEFaN4',
    appId: '1:715110019947:ios:f37288d0b6a2ae491bd22e',
    messagingSenderId: '715110019947',
    projectId: 'apps-3e547',
    storageBucket: 'apps-3e547.appspot.com',
    iosBundleId: 'com.example.apps.RunnerTests',
  );
}
